services:
  # PostgreSQL 資料庫服務
  db:
    image: postgres:15-alpine
    container_name: goat-nutrition-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-goat_nutrition_db}
      POSTGRES_USER: ${POSTGRES_USER:-goat_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-goat_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-goat_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - goat-network

  # 後端服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: goat-nutrition-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # 資料庫配置
      DATABASE_URL: postgresql://${POSTGRES_USER:-goat_user}:${POSTGRES_PASSWORD:-goat_password}@db:5432/${POSTGRES_DB:-goat_nutrition_db}
      
      # 應用程式配置
      SECRET_KEY: ${SECRET_KEY:-your-very-secret-key-change-in-production}
      FLASK_ENV: ${FLASK_ENV:-production}
      FLASK_DEBUG: ${FLASK_DEBUG:-False}
      
      # CORS 配置
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost,http://127.0.0.1}
      
      # Google API
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-your-gemini-api-key}
    volumes:
      - ./backend/logs:/app/logs
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/auth/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - goat-network

  # 前端服務
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: goat-nutrition-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - goat-network

# 資料卷定義
volumes:
  postgres_data:
    driver: local

# 網路定義
networks:
  goat-network:
    driver: bridge
