"""Add ESG fields to Sheep and SheepEvent models

Revision ID: a6d3b4664bd0
Revises: 
Create Date: 2025-07-27 13:18:28.441948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d3b4664bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manure_management', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('primary_forage_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('welfare_score', sa.Integer(), nullable=True))

    with op.batch_alter_table('sheep_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('withdrawal_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheep_event', schema=None) as batch_op:
        batch_op.drop_column('withdrawal_days')
        batch_op.drop_column('medication')

    with op.batch_alter_table('sheep', schema=None) as batch_op:
        batch_op.drop_column('welfare_score')
        batch_op.drop_column('primary_forage_type')
        batch_op.drop_column('manure_management')

    # ### end Alembic commands ###